### PR TITLE
Add docs for UAPI Response class.

### PR DESCRIPTION
**Pull request by FGasper**
Issue #6

### CODE REVIEW

**Review by rwp0 — APPROVED** [review]
Thanks, looks good now!

**Comment by rwp0** [comment]
Will this documentation be released on CPAN upon merging of the PR or we need to wait some time for the whole distribution release (or they are the same)?

**Comment by FGasper** [comment]
> Will this documentation be released on CPAN upon merging of the PR or we need to wait some time for the whole distribution release (or they are the same)?

There’s a separate CPAN release process, but it’s pretty ad-hoc. I’ll see if I can get it pushed this week.

Thanks!

**Comment by rwp0** [comment]
Yeah, it will also make it dated more recent than [PublicAPI](https://metacpan.org/pod/cPanel::PublicAPI).

[APIClient](https://metacpan.org/dist/cPanel-APIClient): OCT 27, 2020
[PublicAPI](https://metacpan.org/pod/cPanel::PublicAPI): JAN 27, 2021

Which affects how people adopt a library distribution for particular use case :-)

I initially went with PublicAPI due to the release date being more recent, then discovered that it doesn't support UAPI :-(

**Review by dustin-s — APPROVED** [review]
Changes look good. Just POD additions. Since only POD was added, copyright doesn't need to be updated.

**Pull request merged**
